import { randomUUID } from "node:crypto";
import { composeServiceRight, type CreateServiceRightInput, type ServiceRight } from "@skillpass-care/core";
import type { CareCoverageStore } from "@skillpass-care/care-store";
import { SkillPassError, type AuthorizationEvidence, type ClaimMutationOptions, type EntitlementStatus, type LedgerHealth, type LedgerListFilter, type MutationOptions, type ServiceEventListFilter } from "@skillpass-care/shared";
import { hashAuthorizationEvidence } from "./ownership-memory.js";
import type { ServiceRightLedger, SkillPassOwnershipPort } from "./types.js";

export class SplitServiceRightLedger implements ServiceRightLedger {
  constructor(public readonly ownership:SkillPassOwnershipPort, public readonly care:CareCoverageStore){}
  async issue(input:CreateServiceRightInput){const id=input.id??`ent-${randomUUID()}`;if(!this.ownership.issueDemo)throw new SkillPassError("NOT_IMPLEMENTED","issuance belongs to canonical SkillPass client",503);const ownership=await this.ownership.issueDemo(id,input.owner,input.transferable);const coverage=await this.care.create({...input,id});return composeServiceRight(coverage,ownership);}
  async get(id:string){const [c,o]=await Promise.all([this.care.get(id),this.ownership.resolve(id)]);return c&&o?composeServiceRight(c,o):undefined;}
  async list(filter:LedgerListFilter={}){const coverages=await this.care.list({issuerId:filter.issuerId,providerId:filter.providerId});const out:ServiceRight[]=[];for(const c of coverages){const o=await this.ownership.resolve(c.id);if(o&&(!filter.owner||o.owner===filter.owner))out.push(composeServiceRight(c,o));}return out;}
  async transfer(id:string,from:string,to:string,_options:MutationOptions){if(!this.ownership.transfer)throw new SkillPassError("NOT_IMPLEMENTED","transfer must be submitted through SkillPass wallet/client",503);await this.ownership.transfer(id,from,to);const r=await this.get(id);if(!r)throw new SkillPassError("NOT_FOUND","entitlement not found",404);return r;}
  async claim(id:string,claimant:string,providerId:string,options:ClaimMutationOptions & {authorizationEvidence?:AuthorizationEvidence}){const evidence=options.authorizationEvidence??await this.ownership.authorize({entitlementId:id,claimant,providerId,requestHash:options.requestHash});if(!evidence.allowed||!evidence.stateRef)throw new SkillPassError("FORBIDDEN",`claim denied: ${evidence.reason}`,403);if(evidence.claimant!==claimant||evidence.providerId!==providerId||evidence.entitlementId!==id||evidence.requestHash!==options.requestHash)throw new SkillPassError("FORBIDDEN","authorization evidence is not bound to this Care request",403);const result=await this.care.consume(id,{claimant,providerId,authorizationStateRef:evidence.stateRef,authorizationEvidenceHash:hashAuthorizationEvidence(evidence),assertStateRefCurrent:(ref)=>this.ownership.assertStateRefCurrent(ref)},options);const owner=await this.ownership.resolve(id);if(!owner)throw new SkillPassError("STATE_REF_STALE","SkillPass capability no longer resolves",409);return composeServiceRight(result.coverage,owner);}
  async listServiceEvents(id:string,filter:ServiceEventListFilter={}){return this.care.listServiceEvents(id,filter);}
  async setStatus(id:string,issuerId:string,status:EntitlementStatus,options:MutationOptions){const c=await this.care.setStatus(id,issuerId,status,options);const o=await this.ownership.resolve(id);if(!o)throw new SkillPassError("NOT_FOUND","SkillPass capability not found",404);return composeServiceRight(c,o);}
  async health():Promise<LedgerHealth>{const [a,b]=await Promise.all([this.ownership.health(),this.care.health()]);return{mode:b.mode,ready:a.ready&&b.ready,detail:`ownership=${a.detail}; care=${b.detail}`};}
  async resetDemo(){await this.ownership.reset?.();await this.care.reset?.();return this.issue({issuerId:"seller-demo",productCommitment:"sha256:42f4dc06f496e6209f50c0849c4fb14d0b2a4f752d636a28bb7e091ea462863c",owner:"alice",serviceClass:"STANDARD_90D",remainingClaims:3,expiresAt:"2099-12-31T23:59:59.000Z",transferable:true,acceptedProviderIds:["repair-a","repair-b"]});}
}
