import { Pool, type PoolClient } from "pg";
import { SkillPassError, type ClaimMutationOptions, type EntitlementStatus, type LedgerHealth, type LedgerListFilter, type MutationOptions, type ServiceEventListFilter, type ServiceEventRecord } from "@skillpass-care/shared";
import { SERVICE_RIGHT_SCHEMA_VERSION, type CareCoverage, type CreateCareCoverageInput } from "@skillpass-care/core";
import type { CareConsumptionContext, CareCoverageStore } from "./types.js";

export class PostgresCareStore implements CareCoverageStore {
  private readonly pool: Pool;
  constructor(connectionString: string | Pool) { this.pool = typeof connectionString === "string" ? new Pool({ connectionString }) : connectionString; }
  async health(): Promise<LedgerHealth> { try { await this.pool.query("select 1"); return { mode:"postgres", ready:true, detail:"durable PostgreSQL Care store" } as LedgerHealth; } catch(e){ return { mode:"postgres", ready:false, detail:e instanceof Error?e.message:"PostgreSQL unavailable" } as LedgerHealth; } }
  async create(input: CreateCareCoverageInput): Promise<CareCoverage> {
    const client=await this.pool.connect(); try { await client.query("BEGIN"); const id=input.id ?? crypto.randomUUID(); const q=await client.query(`INSERT INTO care_coverage(entitlement_id,issuer_id,product_commitment,service_class,remaining_claims,status,version,transferable,expires_at) VALUES($1,$2,$3,$4,$5,'ACTIVE',1,$6,$7) RETURNING *`,[id,input.issuerId,input.productCommitment,input.serviceClass,input.remainingClaims,input.transferable,input.expiresAt]); for(const p of [...new Set(input.acceptedProviderIds)]) await client.query(`INSERT INTO care_provider_acceptance(entitlement_id,provider_id) VALUES($1,$2)`,[id,p]); await client.query("COMMIT"); return this.inflate(client,q.rows[0]); } catch(e){ await client.query("ROLLBACK"); throw e;} finally{client.release();}
  }
  async get(id:string){ const q=await this.pool.query(`SELECT * FROM care_coverage WHERE entitlement_id=$1`,[id]); if(!q.rowCount)return undefined; return this.inflate(this.pool,q.rows[0]); }
  async list(filter:Omit<LedgerListFilter,"owner">={}) { const q=await this.pool.query(`SELECT DISTINCT c.* FROM care_coverage c LEFT JOIN care_provider_acceptance p ON p.entitlement_id=c.entitlement_id WHERE ($1::text IS NULL OR c.issuer_id=$1) AND ($2::text IS NULL OR p.provider_id=$2) ORDER BY c.created_at`,[filter.issuerId??null,filter.providerId??null]); return Promise.all(q.rows.map(r=>this.inflate(this.pool,r))); }
  async consume(id:string, context:CareConsumptionContext, options:ClaimMutationOptions){
    const client=await this.pool.connect(); try { await client.query("BEGIN"); const prior=await client.query(`SELECT * FROM care_service_event WHERE provider_id=$1 AND event_id=$2 FOR UPDATE`,[context.providerId,options.serviceEventId]); if(prior.rowCount){const e=mapEvent(prior.rows[0]); const same=e.entitlementId===id&&e.claimant===context.claimant&&e.requestHash===options.requestHash&&e.authorizationStateRef===context.authorizationStateRef&&e.serviceType===(options.serviceType??"REPAIR")&&e.unitsConsumed===(options.unitsConsumed??1); if(!same) throw new SkillPassError("IDEMPOTENCY_CONFLICT","serviceEventId was already used for a different service request",409); const c=await this.getWithClient(client,id); await client.query("COMMIT"); return {coverage:c,event:e};}
      await context.assertStateRefCurrent(context.authorizationStateRef);
      const units=options.unitsConsumed??1; const updated=await client.query(`UPDATE care_coverage SET remaining_claims=remaining_claims-$1, version=version+1, updated_at=now() WHERE entitlement_id=$2 AND version=$3 AND status='ACTIVE' AND expires_at>now() AND remaining_claims >= $1 RETURNING *`,[units,id,options.expectedVersion]); if(updated.rowCount!==1) throw new SkillPassError("VERSION_CONFLICT","coverage changed, inactive, expired, or insufficient",409);
      const before=Number(updated.rows[0].version)-1; const after=Number(updated.rows[0].version); const serviceType=options.serviceType??"REPAIR";
      await client.query(`INSERT INTO care_service_event(provider_id,event_id,entitlement_id,claimant,service_type,units_consumed,request_hash,authorization_state_ref,authorization_evidence_hash,entitlement_version_before,entitlement_version_after,remaining_claims_after,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,now())`,[context.providerId,options.serviceEventId,id,context.claimant,serviceType,units,options.requestHash,context.authorizationStateRef,context.authorizationEvidenceHash,before,after,updated.rows[0].remaining_claims]);
      // Final fail-closed liveness check immediately before COMMIT.
      await context.assertStateRefCurrent(context.authorizationStateRef);
      await client.query("COMMIT"); const coverage=await this.inflate(this.pool,updated.rows[0]); const eventQ=await this.pool.query(`SELECT * FROM care_service_event WHERE provider_id=$1 AND event_id=$2`,[context.providerId,options.serviceEventId]); return {coverage,event:mapEvent(eventQ.rows[0])};
    } catch(e){await client.query("ROLLBACK"); throw e;} finally{client.release();}
  }
  async listServiceEvents(id:string,filter:ServiceEventListFilter={}){const q=await this.pool.query(`SELECT * FROM care_service_event WHERE entitlement_id=$1 AND ($2::text IS NULL OR provider_id=$2) ORDER BY occurred_at,event_id`,[id,filter.providerId??null]); return q.rows.map(mapEvent);}
  async setStatus(id:string,issuerId:string,status:EntitlementStatus,options:MutationOptions){const q=await this.pool.query(`UPDATE care_coverage SET status=$1,version=version+1,updated_at=now() WHERE entitlement_id=$2 AND issuer_id=$3 AND version=$4 AND status<>'REVOKED' RETURNING *`,[status,id,issuerId,options.expectedVersion]); if(q.rowCount!==1) throw new SkillPassError("VERSION_CONFLICT","coverage status update rejected",409); return this.inflate(this.pool,q.rows[0]);}
  private async getWithClient(client:PoolClient,id:string){const q=await client.query(`SELECT * FROM care_coverage WHERE entitlement_id=$1`,[id]); if(!q.rowCount) throw new SkillPassError("NOT_FOUND","entitlement not found",404); return this.inflate(client,q.rows[0]);}
  private async inflate(queryable:{query:(q:string,p?:unknown[])=>Promise<any>},r:any):Promise<CareCoverage>{const p=await queryable.query(`SELECT provider_id FROM care_provider_acceptance WHERE entitlement_id=$1 ORDER BY provider_id`,[r.entitlement_id]); return {schemaVersion:SERVICE_RIGHT_SCHEMA_VERSION,id:r.entitlement_id,issuerId:r.issuer_id,productCommitment:r.product_commitment,serviceClass:r.service_class,remainingClaims:Number(r.remaining_claims),expiresAt:new Date(r.expires_at).toISOString(),transferable:r.transferable,acceptedProviderIds:p.rows.map((x:any)=>x.provider_id),status:r.status,version:Number(r.version),createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()};}
}
function mapEvent(r:any):ServiceEventRecord{return{eventVersion:2,eventId:r.event_id,entitlementId:r.entitlement_id,providerId:r.provider_id,claimant:r.claimant,serviceType:r.service_type,unitsConsumed:Number(r.units_consumed),requestHash:r.request_hash,authorizationStateRef:r.authorization_state_ref,authorizationEvidenceHash:r.authorization_evidence_hash,entitlementVersionBefore:Number(r.entitlement_version_before),entitlementVersionAfter:Number(r.entitlement_version_after),remainingClaimsAfter:Number(r.remaining_claims_after),occurredAt:new Date(r.occurred_at).toISOString()};}
