FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY apps ./apps
COPY packages ./packages
COPY tsconfig.base.json ./
RUN npm install
RUN npm run build -w @skillpass/api
EXPOSE 8787
CMD ["npm","run","start","-w","@skillpass/api"]
